app.py
from flask import Flask, request

from routes.home_routes import home

# Initialize Flask app
app = Flask(__name__, template_folder='templates', static_url_path='/static', static_folder='static')

# Register for home route
app.register_blueprint(home, url_prefix='/')

# App config
app.config['SECRET_KEY'] = 'secret-key'
app.config['UPLOAD_FOLDER'] = 'uploads'
app.config['FACES_FOLDER'] = 'faces'
app.config['TEMPLATES_AUTO_RELOAD'] = True
app.use_reloader = True


# Remove jinja2 cache
@app.before_request
def clear_jinja_cache():
	if 'localhost' in request.host_url or '0.0.0.0' in request.host_url:
		app.jinja_env.cache = {}


# run project
if __name__ == '__main__':
	app.run(extra_dirs=['uploads', 'faces'])

routes/home_routes.py
import base64
import os
import uuid

from flask import Blueprint, render_template, request, current_app

from dto.FaceDetectionDTO import FaceDetectionDTO
from dto.FaceRecognitionDTO import FaceRecognitionDTO
from services.CNNFaceAuthenticationService import CNNFaceAuthenticationService
from services.DlibCNNFaceAuthenticationService import DlibCNNFaceAuthenticationService
from services.EigenFaceAuthenticationService import EigenFaceAuthenticationService
from services.FaceDetectionService import FaceDetectionService

home = Blueprint('home', __name__)

# create faces folder if not exists
os.makedirs('faces', exist_ok=True)

# Khởi tạo service nhận diện khuôn mặt
# Trong constructor load file json ra để đỡ train lại
cnnFaceAuthenticationService = CNNFaceAuthenticationService("faces")
dlibCNNFaceAuthenticationService = DlibCNNFaceAuthenticationService("faces")
eigenFaceAuthenticationService = EigenFaceAuthenticationService("faces")


@home.route('/', methods=['GET'])
@home.route('/home', methods=['GET'])
@home.route('/login', methods=['GET'])
def index():
	return render_template('login.html')


@home.route('/login', methods=['POST'])
def post_login():
	# Lấy ảm ra dưới dạng Base64
	base64_str = request.form['image']
	save_path = save_image(base64_str)

	# Đếm khuôn mặt bằng Haar cascade (OpenCV)
	faces_detected_haar_cascade = FaceDetectionService.detect_faces_by_haar_cascade_open_cv(save_path)
	# Đếm khuôn mặt bằng HOG (Face Recognition)
	faces_detected_hog = FaceDetectionService.detect_faces_by_hog_face_recognition(save_path)

	# Nhận diện khuôn mặt bằng CNN (Face Recognition)
	cnn_result = cnnFaceAuthenticationService.recognize_faces(save_path)
	# Nhận diện khuôn mặt bằng CNN (Dlib)
	dlib_cnn_result = dlibCNNFaceAuthenticationService.recognize_faces(save_path)
	# Nhận diện khuôn mặt bằng Eigenface
	eigen_result = eigenFaceAuthenticationService.recognize_faces(save_path)
	# Tạo FaceDetectionDTO để truyền vào template
	face_detection_dto = FaceDetectionDTO(
		faces_detected_haar_cascade,
		faces_detected_hog
	)
	# Tạo FaceRecognitionDTO để truyền vào template
	face_recognition_dto = FaceRecognitionDTO(
		cnn_result,
		dlib_cnn_result,
		eigen_result
	)

	return render_template('result.html', face_detection_dto=face_detection_dto, face_recognition_dto=face_recognition_dto)


def save_image(base64_str):
	base64_data = base64_str.split(',')[1]
	image_data = base64.b64decode(base64_data)

	# Đặt đường dẫn lưu trữ ảnh
	filename = str(uuid.uuid4()) + '.png'
	save_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
	os.makedirs(os.path.dirname(save_path), exist_ok=True)

	# Lưu ảnh
	with open(save_path, 'wb') as f:
		f.write(image_data)

	return save_path

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            scroll-behavior: smooth;
        }

        body {
            font-family: 'Quicksand', 'Roboto', sans-serif;
            font-weight: 500;
            background-color: white;
            background-image: linear-gradient(23deg, rgba(202, 202, 202, 0.02) 0%, rgba(202, 202, 202, 0.02) 13%, transparent 13%, transparent 80%, rgba(11, 11, 11, 0.02) 80%, rgba(11, 11, 11, 0.02) 100%), linear-gradient(42deg, rgba(98, 98, 98, 0.02) 0%, rgba(98, 98, 98, 0.02) 36%, transparent 36%, transparent 77%, rgba(252, 252, 252, 0.02) 77%, rgba(252, 252, 252, 0.02) 100%), linear-gradient(286deg, rgba(173, 173, 173, 0.02) 0%, rgba(173, 173, 173, 0.02) 2%, transparent 2%, transparent 12%, rgba(59, 59, 59, 0.02) 12%, rgba(59, 59, 59, 0.02) 100%), linear-gradient(77deg, rgba(87, 87, 87, 0.02) 0%, rgba(87, 87, 87, 0.02) 18%, transparent 18%, transparent 55%, rgba(247, 247, 247, 0.02) 55%, rgba(247, 247, 247, 0.02) 100%), linear-gradient(90deg, rgb(255, 255, 255), rgb(255, 255, 255));
        }

        .card {
            box-shadow: rgba(0, 0, 0, 0.1) 0px 10px 10px -5px, rgba(0, 0, 0, 0.04) 0px 10px 10px -5px;
        }

        .btn {
            box-shadow: rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px;
            transition: .2s;
        }

        .btn:hover {
            box-shadow: rgba(0, 0, 0, 0.2) 0px 10px 15px -3px, rgba(0, 0, 0, 0.1) 0px 4px 6px -2px;
        }
    </style>
</head>
<body>

<div class="container">
    <header class="my-5">
        <h1>
            {{ title }}
        </h1>
    </header>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/login.html
{% extends "base.html" %}

{% set title = "Đăng nhập" %}
{% set action = "/login" %}

{% block content %}
    <div class="card">
        <div class="card-header">
            Xác thực khuôn mặt
        </div>
        <div class="card-body">
            <div class="row">
                <video class="col-12 col-lg-6 p-0" id="video" width="640" height="480" autoplay style="object-fit: cover;"></video>
                <canvas class="col-12 col-lg-6  p-0" id="canvas" width="640" height="480" style="object-fit: cover;"></canvas>
                <br>
            </div>
            <div class="row">
                <div class="col-6 mx-auto">
                    <form class="mt-3" id="form" action="{{ action }}" method="post">
                        <input class="form-control" type="file" name="file" id="file">
                        <input class="form-control invisible" type="text" name="image" id="image" value="">
                    </form>
                    <button class="btn btn-success d-flex ms-auto" id="snap">{{ title }}</button>
                </div>
            </div>
        </div>
    </div>

    <script src="../static/js/handle_authentication.js"></script>

{% endblock %}

templates/result.html
{% extends "base.html" %}

{% set title = "Kết quả" %}
{% block content %}
    <div class="card">
        <div class="card-header">
            Thông tin kết quả
        </div>
        <div class="card-body">
            <h3>Các khuôn mặt được xác định ở vị trí:</h3>
            <p>Haar cascade: Số lượng: {{ face_detection_dto.faces_detected_haar_cascade|length }}</p>
            <ul>
                {% for location in face_detection_dto.faces_detected_haar_cascade %}
                    <li>{{ location }}</li>
                {% endfor %}
            </ul>
            <p>HOG: Số lượng: {{ face_detection_dto.faces_detected_hog|length }}</p>
            <ul>
                {% for location in face_detection_dto.faces_detected_hog %}
                    <li>{{ location }}</li>
                {% endfor %}
            </ul>
            <hr>
            <h3>Kết quả nhận diện khuôn mặt:</h3>
            <p>Kết quả nhận diện của phương pháp CNN (Triển khai qua thư viện Face recognition): </p>
            {% if face_recognition_dto.cnn_result|length == 0 %}
                <li>Không có kết quả</li>
            {% else %}
                <ul>
                    {% for result in face_recognition_dto.cnn_result %}
                        <li>{{ result }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <hr>
            <p>Kết quả nhận diện của phương pháp CNN (Triển khai qua thư viện Dlib): </p>
            {% if face_recognition_dto.dlib_cnn_result|length == 0 %}
                <li>Không có kết quả</li>
            {% else %}
                <ul>
                    {% for result in face_recognition_dto.dlib_cnn_result %}
                        <li>{{ result }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <hr>
            <p>(Chưa hoàn thiện) Kết quả nhận diện của phương pháp Eigenfaces có thể là: </p>
            {% if face_recognition_dto.eigen_result|length == 0 %}
                <li>Không có kết quả</li>
            {% else %}
                <ul>
                    {% for result in face_recognition_dto.eigen_result %}
                        <li>{{ result }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <a class="btn btn-success" href="{{ url_for('home.post_login') }}">Quay về trang đăng nhập</a>
        </div>
    </div>
{% endblock %}